config/routes.rb
 Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :feedbacks
  resources :courses do
  resources :comments
end
  resources :plans do
    resources :suggestions
  end
  resources :requests do
    resources :suggestions
  end
  resources :requests
          resources :users
          resources :microposts, only: [:create, :destroy, :index, :show] do
            resources :reviews, except: [:show, :index]
          end
          resources :sessions, only: [:new, :create, :destroy]
          resources :microposts, only: [:create, :destroy, :index, :show]

          root 'static_pages#home'

          get 'help'    => 'static_pages#help'
          get 'request'    => 'static_pages#request'
          get 'about'   => 'static_pages#about'
          get 'contact' => 'static_pages#contact'

          get 'signup'  => 'users#new'
          get    'login'   => 'sessions#new'
          post   'login'   => 'sessions#create'
          delete 'logout'  => 'sessions#destroy'
          get 'auth/:provider/callback', to: "sessions#thirdpart"
          get'videos' => 'static_pages#videos'
          get'video01' => 'static_pages#video01'
          get'video02' => 'static_pages#video02'
          get'video03' => 'static_pages#video03'
          get'video04' => 'static_pages#video04'
          get'video05' => 'static_pages#video05'

          get  'm_get_all_posts'  => 'microposts#m_get_all_microposts'
          post 'm_register'       => 'users#m_register'
          post 'm_login'          => 'sessions#m_login'
      end

app/models/comment.rb
class Comment < ActiveRecord::Base
  	belongs_to :course
    	validates :content, presence: true, length: { in: 0..30 }
    	  	belongs_to :user

end

app/models/course.rb
class Course < ActiveRecord::Base
  has_many :comments, dependent: :destroy 
   belongs_to :user

end

app/models/feedback.rb
class Feedback < ActiveRecord::Base
	self.inheritance_column = nil
end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
      belongs_to :user 
      has_many :reviews
      default_scope -> { order(created_at: :desc) }   

      validates :user_id, presence: true
      validates :content, presence: true

      has_attached_file :image, styles: { medium: "200x", thumb: "100x100>" }, default_url: "1.jpg"
      validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
      validates_attachment_presence :image
    end

app/models/plan.rb
class Plan < ActiveRecord::Base
	 has_many :suggestions, dependent: :destroy
belongs_to :user
end

app/models/request.rb
class Request < ActiveRecord::Base
	has_many :suggestions
	belongs_to :user
end

app/models/review.rb
class Review < ActiveRecord::Base
	belongs_to :user
	belongs_to :micropost
	
end

app/models/suggestion.rb
class Suggestion < ActiveRecord::Base
  belongs_to :request
  belongs_to :user
    validates :content, presence: true, length: { in: 0..30 }
    
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :microposts, dependent: :destroy
  has_many :feedbacks   
  has_many :reviews, dependent: :destroy
     has_many :comment
     has_many :courses
     has_many :plan
     has_many :suggestion

 	     attr_accessor :remember_token
       before_save { self.email = email.downcase }
       validates :name, presence: true, length: { in: 9..30 }
       VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
       validates :email, presence: true, 
                        format: { with: VALID_EMAIL_REGEX },
                        uniqueness: { case_sensitive: false }
       validates :password, presence: true, length: { minimum: 6 }
       validates :password_confirmation, presence: true
       has_secure_password
       
       
# Returns the hash digest of a string.
      def User.digest(string)
        cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                      BCrypt::Engine.cost
        BCrypt::Password.create(string, cost: cost)
      end
      

      # Returns a random token.
      def User.new_token
        SecureRandom.urlsafe_base64
      end

      # Remembers a user in the database for use in persistent sessions.
      def remember
        self.remember_token = User.new_token
        update_attribute(:remember_digest, User.digest(remember_token))
      end
       # Returns true if the given token matches the digest.
      def authenticated?(remember_token)
        BCrypt::Password.new(remember_digest).is_password?(remember_token)
      end
      
       # Forgets a user.
       def forget
          update_attribute(:remember_digest, nil)
       end
       def feed
                Micropost.where("user_id = ?", id)
        end
       
    end    

app/models/uuser.rb
class Uuser < ActiveRecord::Base

		def self.sign_in_from_omniauth(auth)
      find_by(provider: auth['provider'], uid: auth['uid'],id: auth['id'] ) || create_uuser_from_omniauth(auth)
    end

    def self.create_uuser_from_omniauth(auth)
      create(
        provider: auth['provider'],
        uid: auth['uid'],
        name: auth['info']['name'],
        id: auth['id']
        )       
    end
    
end

app/models/weather_report.rb
class WeatherReport < ActiveRecord::Base
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_action :set_request, only: [:show, :edit, :update, :destroy]

  
  def index
    @requests = Request.all

  end

  
  def show
            @request = Request.find(params[:id])

  end

  
  def new
    @request = Request.new
  end

  
  def edit
  end

  
  def create
    @request = Request.new(request_params)

    
      if @request.save
        redirect_to @request, notice: 'Request was successfully created.' 
        
      else
        render :new 
       
    end
  end

 
  def update
   
      if @request.update(request_params)
        redirect_to @request, notice: 'Request was successfully updated.' 
       
      else
       render :edit 
       
    end
  end

  def destroy
    @request.destroy
    
     redirect_to requests_url, notice: 'Request was successfully destroyed.' 
    
  end

  private
   
    def set_request
      @request = Request.find(params[:id])
    end

    
    def request_params
      params.require(:request).permit(:from_name, :to_name, :status)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	# Remembers a user in a persistent session.
      def remember(user)
        user.remember
        cookies.permanent.signed[:user_id] = user.id
        cookies.permanent[:remember_token] = user.remember_token
      end
      # Returns the user corresponding to the remember token cookie.
      def current_user
        if (user_id = cookies.signed[:user_id])
           user = User.find_by(id: user_id)
           if user && 
                user.authenticated?(cookies[:remember_token])
            @current_user = user
          end
        end
      end
      # Returns true if a user is logged in, false otherwise.
      def logged_in?
        !current_user.nil?
      end

      def logged_in_user
        unless logged_in?
          flash[:notice] = "Please log in"
          redirect_to login_url
        end
    end 
    
      # Returns true if the given user is the current user.
      def current_user?(user)
        user == current_user
      end
      # Forgets a persistent session.      # Forgets a persistent session.
      def forget(user)
          user.forget
          cookies.delete(:user_id)
          cookies.delete(:remember_token)
      end
      # Logs out the current user.
      def log_out
          forget(current_user)
          @current_user = nil
      end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/suggestions_help.rb
module SuggestionsHelper
end

app/helpers/users_helper.rb
module UsersHelper

      # Returns the Gravatar (http://gravatar.com/) for the given user.
      def gravatar_for(user, options = { size: 50 })
        gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
        size = options[:size]
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
        image_tag(gravatar_url, alt: user.name, class: "gravatar")
      end 

    end

app/views/requests/_form.html.erb
<%= form_for(@request) do |f| %>
  <% if @request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@request.errors.count, "error") %> prohibited this request from being saved:</h2>

      <ul>
      <% @request.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :from_name %><br>
    <%= f.text_field :from_name , class: "form-control"%>
  </div>
  <div class="form-group">
    <%= f.label :to_name %><br>
    <%= f.text_field :to_name , class: "form-control"%>
  </div>
  <div class="form-group">
    <%= f.label :status %><br>
    <%= f.text_field :status , class: "form-control"%>
  </div>
  <div class="form-group">
    <%= f.submit "Submit" , class: "btn btn-primary" %>
  </div>

  
<% end %>

app/views/requests/edit.html.erb
<body>
<h1><font color=black size=20>Editing Request</font></h1>


<%= render 'form' %>

<%= link_to 'Show', @request %> |
<%= link_to 'Back', requests_path %>
</body>

app/views/requests/index.html.erb
<body>
<h1><p id="notice"><%= notice %></p><h1>

<h1>Message Board</h1>

    <% @requests.each do |request| %>
        <div class="panel panel-primary">
          <div class="panel-heading">
            <h3 class="panel-title">
              From <%= request.from_name %> to <%= request.to_name %></h3>
          </div>
          <div class="panel-body">
            <%= request.status %>
          </div>
          <div class="panel-foot">
            <div class="row">
              <div class="col-md-offset-10 col-md-3">
                <td><%= link_to 'Show', request , class: "btn btn-primary"%>&nbsp&nbsp</td>
                
              </div>
            </div>
      </div>
    </div>
    <% end %>

<br>
<table align="center">
  <tr><td>
<%= link_to 'New request', new_request_path, class: "btn btn-primary"%>
</tr></td>
</table>


</body>

app/views/requests/new.html.erb
<body>
<h1><font color=black size=20>New Request</font></h1>

<%= render 'form' %>

<%= link_to 'Back', requests_path %>
</body>

app/views/requests/show.html.erb
<div class="alert alert-warning">

<p id="notice"><%= notice %></p>

<p>
  <strong>From name:</strong>
  <%= @request.from_name %>
</p>

<p>
  <strong>To name:</strong>
  <%= @request.to_name %>
</p>

<p>
  <strong>Status:</strong>
  <%= @request.status %>
</p>
<% @request.suggestions.each do |suggestion| %>
<p>
  <strong>Comment by <%= suggestion.user.name %>:
  </strong>
  

  <p><%= suggestion.content %></P>
  


  <%end%>

</p>




<h2>Add a comment:</h2>
<%= form_for([@request, @request.suggestions.build]) do |f| %>
   <div class = "center">
     <%= f.label :content %></br>
     <%= f.text_field :content, style: "width:600px;height:70px;font-size:50px;margin-bottom:30px"%>

   </div>
   <div class="col-md-offset-1 col-md-7">

<%= f.submit "Create new comment", class: "btn btn-primary " ,style: "width:400px;height:35px;font-size:20px;margin-left:270px;margin-bottom:20px" %>
   </div>
<% end %>
<br><br><br>

</div>


<%= link_to 'Back', requests_path %>

app/views/requests/suggestion.html.erb
<body>
<h2><p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @request.name %>
</p>


</h2>
<div class="alert alert-info fade in">
<h2>Comments</h2>
<% @request.suggestions.each do |comment| %>

  <p>
    <strong>Comment:</strong>
    <%= comment.content %>
  </p>
 <p>
  <%= link_to 'Destroy Comment', [comment.product, comment],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
</p>
<% end %>
 </div>

<h2>Add a comment:</h2>
<%= form_for([@request, @request.suggestions.build]) do |f| %>
   <div class = "center">
   <%= f.label :content %>
   <%= f.text_field :content%>

   </div>
   <div class = "center">
<%= f.submit "Create new comment", class: "btn btn-large btn-primary" %>
   </div>
<% end %>




</body>


<%= link_to 'Edit', edit_course_path(@course) %> |
<%= link_to 'Back', courses_path %>