config/routes.rb
 Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :feedbacks
  resources :courses do
  resources :comments
end
  resources :plans do
    resources :suggestions
  end
  resources :requests do
    resources :suggestions
  end
  resources :requests
          resources :users
          resources :microposts, only: [:create, :destroy, :index, :show] do
            resources :reviews, except: [:show, :index]
          end
          resources :sessions, only: [:new, :create, :destroy]
          resources :microposts, only: [:create, :destroy, :index, :show]

          root 'static_pages#home'

          get 'help'    => 'static_pages#help'
          get 'request'    => 'static_pages#request'
          get 'about'   => 'static_pages#about'
          get 'contact' => 'static_pages#contact'

          get 'signup'  => 'users#new'
          get    'login'   => 'sessions#new'
          post   'login'   => 'sessions#create'
          delete 'logout'  => 'sessions#destroy'
          get 'auth/:provider/callback', to: "sessions#thirdpart"
          get'videos' => 'static_pages#videos'
          get'video01' => 'static_pages#video01'
          get'video02' => 'static_pages#video02'
          get'video03' => 'static_pages#video03'
          get'video04' => 'static_pages#video04'
          get'video05' => 'static_pages#video05'

          get  'm_get_all_posts'  => 'microposts#m_get_all_microposts'
          post 'm_register'       => 'users#m_register'
          post 'm_login'          => 'sessions#m_login'
      end

app/models/comment.rb
class Comment < ActiveRecord::Base
  	belongs_to :course
    	validates :content, presence: true, length: { in: 0..30 }
    	  	belongs_to :user

end

app/models/course.rb
class Course < ActiveRecord::Base
  has_many :comments, dependent: :destroy 
   belongs_to :user

end

app/models/feedback.rb
class Feedback < ActiveRecord::Base
	self.inheritance_column = nil
end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
      belongs_to :user 
      has_many :reviews
      default_scope -> { order(created_at: :desc) }   

      validates :user_id, presence: true
      validates :content, presence: true

      has_attached_file :image, styles: { medium: "200x", thumb: "100x100>" }, default_url: "1.jpg"
      validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
      validates_attachment_presence :image
    end

app/models/plan.rb
class Plan < ActiveRecord::Base
	 has_many :suggestions, dependent: :destroy
belongs_to :user
end

app/models/request.rb
class Request < ActiveRecord::Base
	has_many :suggestions
	belongs_to :user
end

app/models/review.rb
class Review < ActiveRecord::Base
	belongs_to :user
	belongs_to :micropost
	
end

app/models/suggestion.rb
class Suggestion < ActiveRecord::Base
  belongs_to :request
  belongs_to :user
    validates :content, presence: true, length: { in: 0..30 }
    
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :microposts, dependent: :destroy
  has_many :feedbacks   
  has_many :reviews, dependent: :destroy
     has_many :comment
     has_many :courses
     has_many :plan
     has_many :suggestion

 	     attr_accessor :remember_token
       before_save { self.email = email.downcase }
       validates :name, presence: true, length: { in: 9..30 }
       VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
       validates :email, presence: true, 
                        format: { with: VALID_EMAIL_REGEX },
                        uniqueness: { case_sensitive: false }
       validates :password, presence: true, length: { minimum: 6 }
       validates :password_confirmation, presence: true
       has_secure_password
       
       
# Returns the hash digest of a string.
      def User.digest(string)
        cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                      BCrypt::Engine.cost
        BCrypt::Password.create(string, cost: cost)
      end
      

      # Returns a random token.
      def User.new_token
        SecureRandom.urlsafe_base64
      end

      # Remembers a user in the database for use in persistent sessions.
      def remember
        self.remember_token = User.new_token
        update_attribute(:remember_digest, User.digest(remember_token))
      end
       # Returns true if the given token matches the digest.
      def authenticated?(remember_token)
        BCrypt::Password.new(remember_digest).is_password?(remember_token)
      end
      
       # Forgets a user.
       def forget
          update_attribute(:remember_digest, nil)
       end
       def feed
                Micropost.where("user_id = ?", id)
        end
       
    end    

app/models/uuser.rb
class Uuser < ActiveRecord::Base

		def self.sign_in_from_omniauth(auth)
      find_by(provider: auth['provider'], uid: auth['uid'],id: auth['id'] ) || create_uuser_from_omniauth(auth)
    end

    def self.create_uuser_from_omniauth(auth)
      create(
        provider: auth['provider'],
        uid: auth['uid'],
        name: auth['info']['name'],
        id: auth['id']
        )       
    end
    
end

app/models/weather_report.rb
class WeatherReport < ActiveRecord::Base
end

app/controllers/feedbacks_controller.rb
class FeedbacksController < ApplicationController
  before_action :set_feedback, only: [:show, :edit, :update, :destroy]

  
  def index
    @feedbacks = Feedback.all
  end

  
  def show
  end

  
  def new
    @feedback = Feedback.new
  end

  
  def edit
  end

  def create
    @feedback = Feedback.new(feedback_params)

    
      if @feedback.save
        redirect_to @feedback, notice: 'Feedback was successfully created.'
        
      else
       render :new 
        
    end
  end

  
  def update
   
      if @feedback.update(feedback_params)
        
        render :show, status: :ok, location: @feedback 
      else 
        render :edit 
       
    end
  end

 
  def destroy
    @feedback.destroy
    
       redirect_to feedbacks_url, notice: 'Feedback was successfully destroyed.' 
     
  end

  private
    
    def set_feedback
      @feedback = Feedback.find(params[:id])
    end

    
    def feedback_params
      params.require(:feedback).permit(:type, :comment, :star)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	# Remembers a user in a persistent session.
      def remember(user)
        user.remember
        cookies.permanent.signed[:user_id] = user.id
        cookies.permanent[:remember_token] = user.remember_token
      end
      # Returns the user corresponding to the remember token cookie.
      def current_user
        if (user_id = cookies.signed[:user_id])
           user = User.find_by(id: user_id)
           if user && 
                user.authenticated?(cookies[:remember_token])
            @current_user = user
          end
        end
      end
      # Returns true if a user is logged in, false otherwise.
      def logged_in?
        !current_user.nil?
      end

      def logged_in_user
        unless logged_in?
          flash[:notice] = "Please log in"
          redirect_to login_url
        end
    end 
    
      # Returns true if the given user is the current user.
      def current_user?(user)
        user == current_user
      end
      # Forgets a persistent session.      # Forgets a persistent session.
      def forget(user)
          user.forget
          cookies.delete(:user_id)
          cookies.delete(:remember_token)
      end
      # Logs out the current user.
      def log_out
          forget(current_user)
          @current_user = nil
      end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/suggestions_help.rb
module SuggestionsHelper
end

app/helpers/users_helper.rb
module UsersHelper

      # Returns the Gravatar (http://gravatar.com/) for the given user.
      def gravatar_for(user, options = { size: 50 })
        gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
        size = options[:size]
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
        image_tag(gravatar_url, alt: user.name, class: "gravatar")
      end 

    end

app/views/feedbacks/_form.html.erb
<%= form_for(@feedback) do |f| %>
  <% if @feedback.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@feedback.errors.count, "error") %> prohibited this feedback from being saved:</h2>

      <ul>
      <% @feedback.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :star %><br>
    <%= f.number_field :star ,class: "form-control"%>
  </div>
  <div class="form-group">
    <%= f.label :type %><br>
    <%= f.text_field :type ,class: "form-control"%>
  </div>
  <div class="form-group">
    <%= f.label :comment %><br>
    <%= f.text_field :comment ,class: "form-control"%>
  </div>

  <div class="form-group">
    <%= f.submit "Add Feedback", class: "btn btn-primary"%>
  </div>
<% end %>

app/views/feedbacks/edit.html.erb
<body>
<h1><font color=black size=20>Editing Feedback</font></h1>

<%= render 'form' %>

<%= link_to 'Show', @feedback %> |
<%= link_to 'Back', feedbacks_path %>
</body>

app/views/feedbacks/index.html.erb
<body>


<h1>Listing Feedbacks</h1>

<table class="table table-striped table-bordered table-hover">
  <thead>
    <tr>
      <th>Type&nbsp&nbsp&nbsp</th>
      <th>Comment&nbsp&nbsp&nbsp</th>
      <th>Star&nbsp&nbsp&nbsp</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @feedbacks.each do |feedback| %>
      <tr>
        <td><%= feedback.type %></font></td>
        <td><%= feedback.comment %></td>
        <td><%= feedback.star%></td>
        <td><font color="#0099FF"><%= link_to 'Show', feedback %></font>&nbsp&nbsp&nbsp</td>
        <td><%= link_to 'Edit', edit_feedback_path(feedback) %>&nbsp&nbsp&nbsp</td>
        <td><%= link_to 'Destroy', feedback, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</body>

<br>
<table align="center">
  <tr><td>
<%= link_to 'New Feedback', new_feedback_path, class: "btn btn-info" %>
</tr></td>
</table>

app/views/feedbacks/new.html.erb
<body>
<h1><font color=blue size=24>New Feedback</font></h1>
<div class="row">
  <div class="col-md-offset-3 col-md-6">
<%= form_for(@feedback) do |f| %>

    <%= f.label :star %>
    <table>
    <tr>
    <td width="70px"><%= f.radio_button :star, '1', :checked => true %> rate one</td>
    <td width="70px"><%= f.radio_button :star, '2' %> rate two</td>
    <td width="70px"><%= f.radio_button :star, '3' %> rate three</td>
    <td width="70px"><%= f.radio_button :star, '4' %> rate four</td>
    <td width="70px"><%= f.radio_button :star, '5' %> rate five</td>
    </tr>
    </table>
    <br>
    <%= render 'form'%>


<% end %>
  </div>
</div>

</body>





<%= link_to 'Back', feedbacks_path %>

app/views/feedbacks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Type:</strong>
  <%= @feedback.type %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @feedback.comment %>
</p>

<p>
  <strong>Star:</strong>
  <%= @feedback.star %>
</p>

<%= link_to 'Edit', edit_feedback_path(@feedback) %> |
<%= link_to 'Back', feedbacks_path %>
</stytle>
</head>
</html>