config/routes.rb
 Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :feedbacks
  resources :courses do
  resources :comments
end
  resources :plans do
    resources :suggestions
  end
  resources :requests do
    resources :suggestions
  end
  resources :requests
          resources :users
          resources :microposts, only: [:create, :destroy, :index, :show] do
            resources :reviews, except: [:show, :index]
          end
          resources :sessions, only: [:new, :create, :destroy]
          resources :microposts, only: [:create, :destroy, :index, :show]

          root 'static_pages#home'

          get 'help'    => 'static_pages#help'
          get 'request'    => 'static_pages#request'
          get 'about'   => 'static_pages#about'
          get 'contact' => 'static_pages#contact'

          get 'signup'  => 'users#new'
          get    'login'   => 'sessions#new'
          post   'login'   => 'sessions#create'
          delete 'logout'  => 'sessions#destroy'
          get 'auth/:provider/callback', to: "sessions#thirdpart"
          get'videos' => 'static_pages#videos'
          get'video01' => 'static_pages#video01'
          get'video02' => 'static_pages#video02'
          get'video03' => 'static_pages#video03'
          get'video04' => 'static_pages#video04'
          get'video05' => 'static_pages#video05'

          get  'm_get_all_posts'  => 'microposts#m_get_all_microposts'
          post 'm_register'       => 'users#m_register'
          post 'm_login'          => 'sessions#m_login'
      end

app/models/comment.rb
class Comment < ActiveRecord::Base
  	belongs_to :course
    	validates :content, presence: true, length: { in: 0..30 }
    	  	belongs_to :user

end

app/models/course.rb
class Course < ActiveRecord::Base
  has_many :comments, dependent: :destroy 
   belongs_to :user

end

app/models/feedback.rb
class Feedback < ActiveRecord::Base
	self.inheritance_column = nil
end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
      belongs_to :user 
      has_many :reviews
      default_scope -> { order(created_at: :desc) }   

      validates :user_id, presence: true
      validates :content, presence: true

      has_attached_file :image, styles: { medium: "200x", thumb: "100x100>" }, default_url: "1.jpg"
      validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
      validates_attachment_presence :image
    end

app/models/plan.rb
class Plan < ActiveRecord::Base
	 has_many :suggestions, dependent: :destroy
belongs_to :user
end

app/models/request.rb
class Request < ActiveRecord::Base
	has_many :suggestions
	belongs_to :user
end

app/models/review.rb
class Review < ActiveRecord::Base
	belongs_to :user
	belongs_to :micropost
	
end

app/models/suggestion.rb
class Suggestion < ActiveRecord::Base
  belongs_to :request
  belongs_to :user
    validates :content, presence: true, length: { in: 0..30 }
    
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :microposts, dependent: :destroy
  has_many :feedbacks   
  has_many :reviews, dependent: :destroy
     has_many :comment
     has_many :courses
     has_many :plan
     has_many :suggestion

 	     attr_accessor :remember_token
       before_save { self.email = email.downcase }
       validates :name, presence: true, length: { in: 9..30 }
       VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
       validates :email, presence: true, 
                        format: { with: VALID_EMAIL_REGEX },
                        uniqueness: { case_sensitive: false }
       validates :password, presence: true, length: { minimum: 6 }
       validates :password_confirmation, presence: true
       has_secure_password
       
       
# Returns the hash digest of a string.
      def User.digest(string)
        cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                      BCrypt::Engine.cost
        BCrypt::Password.create(string, cost: cost)
      end
      

      # Returns a random token.
      def User.new_token
        SecureRandom.urlsafe_base64
      end

      # Remembers a user in the database for use in persistent sessions.
      def remember
        self.remember_token = User.new_token
        update_attribute(:remember_digest, User.digest(remember_token))
      end
       # Returns true if the given token matches the digest.
      def authenticated?(remember_token)
        BCrypt::Password.new(remember_digest).is_password?(remember_token)
      end
      
       # Forgets a user.
       def forget
          update_attribute(:remember_digest, nil)
       end
       def feed
                Micropost.where("user_id = ?", id)
        end
       
    end    

app/models/uuser.rb
class Uuser < ActiveRecord::Base

		def self.sign_in_from_omniauth(auth)
      find_by(provider: auth['provider'], uid: auth['uid'],id: auth['id'] ) || create_uuser_from_omniauth(auth)
    end

    def self.create_uuser_from_omniauth(auth)
      create(
        provider: auth['provider'],
        uid: auth['uid'],
        name: auth['info']['name'],
        id: auth['id']
        )       
    end
    
end

app/models/weather_report.rb
class WeatherReport < ActiveRecord::Base
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  before_action :set_plan, only: [:show, :edit, :update, :destroy]


  def index
    @plans = Plan.all
  end

  def show
      @plan = Plan.find(params[:id])
  end


  def new
    @plan = Plan.new
  end


  def edit
  end


  def create
    @plan = Plan.new(plan_params)

    @plan.user_id=current_user.id
      if @plan.save
        redirect_to @plan, notice: 'Plan was successfully created.'

      else
        render :new


    end
  end


  def update

      if @plan.update(plan_params)
      redirect_to @plan, notice: 'Plan was successfully updated.'

      else
       render :edit

    end
  end


  def destroy
    @plan.destroy

       redirect_to plans_url, notice: 'Plan was successfully destroyed.'


  end

  private

    def set_plan
      @plan = Plan.find(params[:id])
    end


    def plan_params
      params.require(:plan).permit(:strat_time, :end_time, :distance, :progress, :state,:user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	# Remembers a user in a persistent session.
      def remember(user)
        user.remember
        cookies.permanent.signed[:user_id] = user.id
        cookies.permanent[:remember_token] = user.remember_token
      end
      # Returns the user corresponding to the remember token cookie.
      def current_user
        if (user_id = cookies.signed[:user_id])
           user = User.find_by(id: user_id)
           if user && 
                user.authenticated?(cookies[:remember_token])
            @current_user = user
          end
        end
      end
      # Returns true if a user is logged in, false otherwise.
      def logged_in?
        !current_user.nil?
      end

      def logged_in_user
        unless logged_in?
          flash[:notice] = "Please log in"
          redirect_to login_url
        end
    end 
    
      # Returns true if the given user is the current user.
      def current_user?(user)
        user == current_user
      end
      # Forgets a persistent session.      # Forgets a persistent session.
      def forget(user)
          user.forget
          cookies.delete(:user_id)
          cookies.delete(:remember_token)
      end
      # Logs out the current user.
      def log_out
          forget(current_user)
          @current_user = nil
      end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/suggestions_help.rb
module SuggestionsHelper
end

app/helpers/users_helper.rb
module UsersHelper

      # Returns the Gravatar (http://gravatar.com/) for the given user.
      def gravatar_for(user, options = { size: 50 })
        gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
        size = options[:size]
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
        image_tag(gravatar_url, alt: user.name, class: "gravatar")
      end 

    end

app/views/plans/_form.html.erb
<%= form_for(@plan) do |f| %>
  <% if @plan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@plan.errors.count, "error") %> prohibited this plan from being saved:</h2>

      <ul>
      <% @plan.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div  class="form-group">
    <%= f.label :strat_time %><br>
    <%= f.text_field :strat_time , class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :end_time %><br>
    <%= f.text_field :end_time , class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :distance %><br>
    <%= f.number_field :distance  , class: "form-control"%>
  </div>
  <div class="form-group">
    <%= f.label :progress ,"Location" %><br>
    <%= f.text_field :progress  , class: "form-control"%>
  </div>
  <div class="form-group">
    <%= f.label :state %><br>
    <%= f.text_field :state , class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit "Submit" , class: "btn btn-primary" %>
  </div>
<% end %>

app/views/plans/edit.html.erb
<body>
<h1><font color=black size=20>Editing Plan</font></h1>

<%= render 'form' %>

<%= link_to 'Show', @plan %> |
<%= link_to 'Back', plans_path %>
</body>

app/views/plans/index.html.erb
<body>

<div class="center jumbotron">
  <div id="myCarousel" class="carousel slide">
   <!-- （Carousel）indicator -->
   <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      <li data-target="#myCarousel" data-slide-to="1"></li>

   </ol>

<div class="carousel-inner">
      <div class="item active">
         <%= image_tag("9.jpg", alt:"First", :size => "1000x150") %>
      </div>

      <div class="item">
         <%= image_tag("10.jpg",:size => "1000x150") %>
      </div>
   </div>
<h1>Listing Plans</h1>
<p id="notice"><%= notice %></p>
<table class="table table-striped table-bordered table-hover">
  <thead>
    <tr>
      <th>Strat time&nbsp&nbsp</th>
      <th>End time&nbsp&nbsp</th>
      <th>Distance&nbsp&nbsp</th>
      <th>Location&nbsp&nbsp</th>
      <th>State&nbsp&nbsp</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @plans.each do |plan| %>
      <tr>
        <td><%= plan.strat_time %></td>
        <td><%= plan.end_time %></td>
        <td><%= plan.distance %></td>
        <td><%= plan.progress %></td>
        <td><%= plan.state %></td>



      <td><%= link_to 'Show', plan %>&nbsp&nbsp</td>
        
      </tr>
    <% end %>
  </tbody>
</table>

<br>
</body>

<table align="center">
  <tr><td>
 <%= link_to 'New Plan', new_plan_path, class: "btn btn-primary" %>
</tr></td>
</table>

app/views/plans/new.html.erb
<body>
<h1><font color=black size=20>New Plan</h1></font>

<%= render 'form' %>

<%= link_to 'Back', plans_path %>
</body>

app/views/plans/show.html.erb
<body>
  <div class="alert alert-info fade in">
   
<p id="notice"><%= notice %></p>

<div class="row">
	<div class="col-md-8">
	<p>
	  <strong>Location:</strong>
	  <br>
	  <iframe
	        width="500"
	        height="400"
	        frameborder="0" style="border:0"
	        src="https://www.google.com/maps/embed/v1/place?key=AIzaSyDSgXnnbTTdfHzBxLvsBruygkc0aTP8RiQ&q=<%= @plan.progress.parameterize %>&zoom=14">
	    </iframe>

	</p>
	</div>
	<div class="col-md-4">
           <br>
           <br>
			<p>
			<strong>Maked by :<%= @plan.user.name %></strong>

			</p>
			<strong>State:<%= @plan.state %></strong>
			<p>
			  <strong>Strat time:</strong>
			  <%= @plan.strat_time %>
			</p>

			<p>
			  <strong>End time:</strong>
			  <%= @plan.end_time %>
			</p>

			<p>
			  <strong>Distance:</strong>
			  <%= @plan.distance %>
			</p>

    </div>

 </div>



<%= link_to 'Back', plans_path %>
</body>

app/views/plans/suggestion.html.erb
<body>
  <h2><p id="notice"><%= notice %></p>


<p>
  <strong>Strat time:</strong>
  <%= @plan.strat_time %>
</p>

<p>
  <strong>End time:</strong>
  <%= @plan.end_time %>
</p>

<p>
  <strong>Distance:</strong>
  <%= @plan.distance %>
</p>

<p>
  <strong>Progress:</strong>
  <%= @plan.progress %>
            <td>Maked by :<%= plan.user.name %></td>

</p>

<p>
  <strong>State:</strong>
  <%= @plan.state %>
</p>
</h2>
<h2>Comments</h2>
<% @plan.suggestions.each do |comment| %>

  <p>
    <strong>Comment:</strong>
    <%= suggestion.content %>
  </p>
 <p>
  <%= link_to 'Destroy Comment', [suggestion.product, suggestion],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
</p>
<% end %>


<h2>Add a comment:</h2>
<%= form_for([@plan, @plan.suggestions.build]) do |f| %>
   <div class = "center">
   <%= f.label :content %>
   <%= f.text_field :content%>

   </div>
   <div class = "center">
<%= f.submit "Create new comment", class: "btn btn-large btn-primary" %>
   </div>
<% end %>
</body>



<%= link_to 'Edit', edit_plan_path(@plan) %> |
<%= link_to 'Back', plans_path %>