config/routes.rb
 Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :feedbacks
  resources :courses do
  resources :comments
end
  resources :plans do
    resources :suggestions
  end
  resources :requests do
    resources :suggestions
  end
  resources :requests
          resources :users
          resources :microposts, only: [:create, :destroy, :index, :show] do
            resources :reviews, except: [:show, :index]
          end
          resources :sessions, only: [:new, :create, :destroy]
          resources :microposts, only: [:create, :destroy, :index, :show]

          root 'static_pages#home'

          get 'help'    => 'static_pages#help'
          get 'request'    => 'static_pages#request'
          get 'about'   => 'static_pages#about'
          get 'contact' => 'static_pages#contact'

          get 'signup'  => 'users#new'
          get    'login'   => 'sessions#new'
          post   'login'   => 'sessions#create'
          delete 'logout'  => 'sessions#destroy'
          get 'auth/:provider/callback', to: "sessions#thirdpart"
          get'videos' => 'static_pages#videos'
          get'video01' => 'static_pages#video01'
          get'video02' => 'static_pages#video02'
          get'video03' => 'static_pages#video03'
          get'video04' => 'static_pages#video04'
          get'video05' => 'static_pages#video05'

          get  'm_get_all_posts'  => 'microposts#m_get_all_microposts'
          post 'm_register'       => 'users#m_register'
          post 'm_login'          => 'sessions#m_login'
      end

app/models/comment.rb
class Comment < ActiveRecord::Base
  	belongs_to :course
    	validates :content, presence: true, length: { in: 0..30 }
    	  	belongs_to :user

end

app/models/course.rb
class Course < ActiveRecord::Base
  has_many :comments, dependent: :destroy 
   belongs_to :user

end

app/models/feedback.rb
class Feedback < ActiveRecord::Base
	self.inheritance_column = nil
end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
      belongs_to :user 
      has_many :reviews
      default_scope -> { order(created_at: :desc) }   

      validates :user_id, presence: true
      validates :content, presence: true

      has_attached_file :image, styles: { medium: "200x", thumb: "100x100>" }, default_url: "1.jpg"
      validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
      validates_attachment_presence :image
    end

app/models/plan.rb
class Plan < ActiveRecord::Base
	 has_many :suggestions, dependent: :destroy
belongs_to :user
end

app/models/request.rb
class Request < ActiveRecord::Base
	has_many :suggestions
	belongs_to :user
end

app/models/review.rb
class Review < ActiveRecord::Base
	belongs_to :user
	belongs_to :micropost
	
end

app/models/suggestion.rb
class Suggestion < ActiveRecord::Base
  belongs_to :request
  belongs_to :user
    validates :content, presence: true, length: { in: 0..30 }
    
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :microposts, dependent: :destroy
  has_many :feedbacks   
  has_many :reviews, dependent: :destroy
     has_many :comment
     has_many :courses
     has_many :plan
     has_many :suggestion

 	     attr_accessor :remember_token
       before_save { self.email = email.downcase }
       validates :name, presence: true, length: { in: 9..30 }
       VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
       validates :email, presence: true, 
                        format: { with: VALID_EMAIL_REGEX },
                        uniqueness: { case_sensitive: false }
       validates :password, presence: true, length: { minimum: 6 }
       validates :password_confirmation, presence: true
       has_secure_password
       
       
# Returns the hash digest of a string.
      def User.digest(string)
        cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                      BCrypt::Engine.cost
        BCrypt::Password.create(string, cost: cost)
      end
      

      # Returns a random token.
      def User.new_token
        SecureRandom.urlsafe_base64
      end

      # Remembers a user in the database for use in persistent sessions.
      def remember
        self.remember_token = User.new_token
        update_attribute(:remember_digest, User.digest(remember_token))
      end
       # Returns true if the given token matches the digest.
      def authenticated?(remember_token)
        BCrypt::Password.new(remember_digest).is_password?(remember_token)
      end
      
       # Forgets a user.
       def forget
          update_attribute(:remember_digest, nil)
       end
       def feed
                Micropost.where("user_id = ?", id)
        end
       
    end    

app/models/uuser.rb
class Uuser < ActiveRecord::Base

		def self.sign_in_from_omniauth(auth)
      find_by(provider: auth['provider'], uid: auth['uid'],id: auth['id'] ) || create_uuser_from_omniauth(auth)
    end

    def self.create_uuser_from_omniauth(auth)
      create(
        provider: auth['provider'],
        uid: auth['uid'],
        name: auth['info']['name'],
        id: auth['id']
        )       
    end
    
end

app/models/weather_report.rb
class WeatherReport < ActiveRecord::Base
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	# Remembers a user in a persistent session.
      def remember(user)
        user.remember
        cookies.permanent.signed[:user_id] = user.id
        cookies.permanent[:remember_token] = user.remember_token
      end
      # Returns the user corresponding to the remember token cookie.
      def current_user
        if (user_id = cookies.signed[:user_id])
           user = User.find_by(id: user_id)
           if user && 
                user.authenticated?(cookies[:remember_token])
            @current_user = user
          end
        end
      end
      # Returns true if a user is logged in, false otherwise.
      def logged_in?
        !current_user.nil?
      end

      def logged_in_user
        unless logged_in?
          flash[:notice] = "Please log in"
          redirect_to login_url
        end
    end 
    
      # Returns true if the given user is the current user.
      def current_user?(user)
        user == current_user
      end
      # Forgets a persistent session.      # Forgets a persistent session.
      def forget(user)
          user.forget
          cookies.delete(:user_id)
          cookies.delete(:remember_token)
      end
      # Logs out the current user.
      def log_out
          forget(current_user)
          @current_user = nil
      end
end

app/helpers/suggestions_help.rb
module SuggestionsHelper
end

app/helpers/users_helper.rb
module UsersHelper

      # Returns the Gravatar (http://gravatar.com/) for the given user.
      def gravatar_for(user, options = { size: 50 })
        gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
        size = options[:size]
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
        image_tag(gravatar_url, alt: user.name, class: "gravatar")
      end 

    end

app/views/layouts/_header.html.erb
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar navbar-inverse" role="navigation">
  <div class="navbar-header">
    <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse">
         <span class="sr-only">Toggle Navigation</span>
         <span class="icon-bar"></span>
         <span class="icon-bar"></span>
         <span class="icon-bar"></span>
       </button>
       <div class="collapse navbar-collapse navbar-responsive-collapse">

  </div>
</div>

<script src="http://libs.baidu.com/jquery/1.9.0/jquery.js"></script>
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
      <div class="container">
        <%= link_to "Fitness", root_path, id: "logo" %>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Home", root_path %></li>


            
            <li><%= link_to "Help", help_path %></li>

            <li><%= link_to "Microposts", microposts_path %></li>
            <% if current_uuser %>
             <li><%= link_to "Make a PLan", plans_path %></li>
             <li><%= link_to "Course", courses_path %></li>
             
              </li>
           <li><%= link_to "Message Board", requests_path %> </li>
           

              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  Account <b class="caret"></b>
                </a>
             <ul class="dropdown-menu">
                  <li><%= link_to "Weather", current_user %></li>
                  <li class="divider"></li>
                  <li>
                    <%= link_to "Log out", logout_path, method: "delete" %>
                  </li>
                </ul>
              </li>
            <% else %>
            <% if logged_in? %>
            <li><%= link_to "Make a PLan", plans_path %></li>
           <li><%= link_to "Course", courses_path %></li>
          
              </li>
           <li><%= link_to "Message Board", requests_path %> </li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  Account <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Weather", current_user %></li>
                  <li class="divider"></li>
                  <li>
                    <%= link_to "Log out", logout_path, method: "delete" %>
                  </li>
                </ul>
              </li>
            <% else %>
              <li><%= link_to "Log in", login_path %></li>
            <% end %>
            <% end %>
          </ul>
        </nav>
      </div>
    </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
    <html>
      <head>
        <title>Sample App | <%= yield(:title) %></title>
        <%= stylesheet_link_tag 'application', media: 'all',
                                               'data-turbolinks-track' => true %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
        <%= csrf_meta_tags %>
        <!--[if lt IE 9]>
          <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
          </script>
        <![endif]-->
      </head>
      <body>
        <%= render 'layouts/header' %>
        <div class="container">
          <% flash.each do |message_type, message| %>    <!-- START NEW CODE  -->
            <div class="alert alert-<%= message_type %>"><%= message %></div>
          <% end %>
          <%= yield %>
          <%= render 'layouts/footer' %>

        </div>
      </body>
    </html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
      <div id="error_explanation">
        <div class="alert alert-danger">
          The form contains <%= pluralize(object.errors.count, "error") %>.
        </div>
        <ul>
        <% object.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
      <ol class="microposts">
        <%= render @feed_items %>
      </ol>
    <% end %>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost, html: { multipart: true } )do |f| %>
   <%= render 'shared/error_messages', object: f.object %>
   <div class="form-group">

       <%= f.text_area :content, placeholder: "Compose new micropost..." , class: "form-control"%>
   </div>

   <div class="form-group">
     <%= f.label :image %><br>
     <%= f.file_field:image, class: "form-control" %>
   </div>

   <%= f.submit "Post", class: "btn btn-primary" %>

   <% end %>

app/views/shared/_stata.html.erb
<% @user ||= current_user %> <div class="stats">
<a href="<%= following_user_path(@user) %>"> <strong id="following" class="stat">
<%= @user.followed_users.count %> </strong>
following
</a>
<a href="<%= followers_user_path(@user) %>">
<strong id="followers" class="stat"> <%= @user.followers.count %>
</strong>
    followers
  </a>
</div>

app/views/shared/_user_info.html.erb
  
  <%= link_to gravatar_for(current_user, size: 50), user_path(current_user) %>
    <h1><%= current_user.name %></h1>
        <span><%= link_to "view weather forecasts", current_user %> </span>
    <span><%= pluralize(current_user.microposts.count, "micropost") %></span>